language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  # Archey package installation (and dependencies).
  - pip3 install .
  # Pylint dependency (see below).
  - pip3 install pylint
script:
  # Simple execution.
  - python3 -m archey
  # Tests suite.
  - python3 setup.py test
  - python3 -m unittest
  # Lint all the things !
  - pylint archey/
