dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
install:
  # Archey package installation (and dependencies).
  - pip3 install .
  # Pylint and Stickytape external dependencies (see below).
  - pip3 install pylint stickytape
script:
  # Simple execution.
  - python3 -m archey
  # Tests suite.
  - python3 setup.py test
  - python3 -m unittest
  # Lint all the things !
  - pylint archey/
  # Build a standalone script from sources.
  - stickytape --add-python-path . --output-file dist/archey.py archey/__main__.py
  - python3 dist/archey.py
