language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # Archey package installation (and dependencies).
  - pip3 install .

  # Pylint, Stickytape and PyInstaller external dependencies (see below).
  - pip3 install pylint stickytape pyinstaller

script:
  # Simple execution.
  - ${VIRTUAL_ENV}/bin/archey
  - python3 -m archey

  # Tests suite.
  - python3 setup.py test
  - python3 -m unittest

  # Lint all the things !
  - pylint archey/

  # Build a standalone script from sources (Stickytape).
  - stickytape --add-python-path . --output-file dist/archey archey/__main__.py
  - python3 dist/archey

  # Build a standalone script from sources (PyInstaller).
  # Currently disabled for Python 3.8, see <pyinstaller/pyinstaller#4311>.
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.8" ]]; then pyinstaller --distpath dist --specpath dist --name archey --onefile archey/__main__.py; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.8" ]]; then ./dist/archey; fi
