dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  # Archey package installation (and dependencies).
  - pip3 install .

  # Pylint and PyInstaller external dependencies (see below).
  - pip3 install pylint pyinstaller

  # Install stickytape from GitHub master (external dependency, see below).
  - git clone https://github.com/mwilliamson/stickytape.git ../stickytape
  - pip3 install ../stickytape/

script:
  # Simple execution.
  - ${VIRTUAL_ENV}/bin/archey
  - python3 -m archey

  # Tests suite.
  - python3 setup.py test
  - python3 -m unittest

  # Lint all the things !
  - pylint archey/

  # Build a standalone script from sources (Stickytape).
  - python3 stickytape/gen-script.py
  - python3 dist/archey

  # Build a standalone script from sources (PyInstaller).
  - pyinstaller --distpath dist pyinstaller/archey.spec
  - ./dist/archey
