"""Elementary OS logo"""

ELEMENTARY = [
    """MMMMMMMMMN0xdoloooooooooolodx0NMMMMMMMMM """,
	"""MMMMMMNOdlldOKNNNKK000KXNXKOdlldONMMMMMM """,
	"""MMMMXkllxKWMWKkxxkkkkkxdoxXWMWKxllkXMMMM """,
	"""MMWOlckNMMW0olxKWMMMMMMN0lcOWMMMNkclOWMM """,
	"""MNd:dXMMWKo:dXWMMMMMMMMMMXl:0MMMMMXd:dNM """,
	"""Nd:kWMMWO:;kWMMMMMMMMMMMMWx;kMMMMMMWk:dN """,
	"""x:xWMMWO;;kWMMMMMMMMMMMMMNo;OMMMMMMMWx;x """,
	""":lXMMMXc'dWMMMMMMMMMMMMMWO:dNMMMMMMMWk,: """,
	""",xWMMMk,;0MMMMMMMMMMMMMWk:oXMMMMMMMWk:,' """,
	""",OMMMWx'cKMMMMMMMMMMMWKocxNMMMMMMMXd:dx, """,
	""",kMMMMk,:0MMMMMMMMWXOxcdKWMMMMMMNOccONk, """,
	""";dWMMMXl'oNMMMMMN0dlld0WMMMMMMNOl:dXWNd; """,
	"""l:0MMMM0:,oXWXOdllxKNWMMMMMWXkl:oKWMM0:l """,
	"""0clKMMMNO:';c:cd0NMMMMMMWKko::dKWMMMXlc0 """,
	"""W0ccdolcc:cl;';ldxxxxxdlc:cdONMMMMWKlcOW """,
	"""MWKl',ok0XWWX0xdlllllldxOKNMMMMMMNkclKWM """,
	"""MMMNkclkXWMMMMMMMWWWMMMMMMMMMMWXklckNMMM """,
	"""MMMMMNkoloOXWMMMMMMMMMMMMMMWXOollkNMMMMM """,
	"""MMMMMMMWKxolodxkO0KKKK0OkxdoloxKWMMMMMMM """,
	"""MMMMMMMMMMWXOoc;,,,,,,,,;coOXWMMMMMMMMMM """
]
