from .user import User
from .hostname import Hostname
from .model import Model
from .kernel import Kernel
from .uptime import Uptime
from .terminal import Terminal
from .packages import Packages
from .temperature import Temperature
from .cpu import CPU
from .gpu import GPU
from .ram import RAM
from .disk import Disk
from .lan_ip import LanIp
from .wan_ip import WanIp
