---
name: Bump Homebrew formula

on:
  # Run when new releases are published.
  release:
    types: [published]
  # Allow manual triggers from GitHub.
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_BUMP_FORMULA_GITHUB_TOKEN }}
          formula: archey4
